<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Pawanuuuu" failures="1" tests="1" name="Standalone Test" time="19.456" errors="0" timestamp="2025-10-23T21:24:31 IST">
  <testcase classname="com.enterprise.tests.StandAloneTest" name="orderTest" time="12.37">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.enterprise.tests.StandAloneTest.orderTest(StandAloneTest.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- orderTest -->
</testsuite> <!-- Standalone Test -->
